package edu.uwm.cs595.goup11.backend.network

import kotlinx.serialization.KSerializer
import java.nio.ByteBuffer
import java.nio.charset.StandardCharsets
import java.util.UUID
import kotlinx.serialization.*
import kotlinx.serialization.json.Json
import kotlinx.serialization.protobuf.ProtoBuf

@OptIn(ExperimentalSerializationApi::class)
@Serializable
data class Message(
    val to: String,
    val from: String,
    val type: MessageType,
    var data: ByteArray? = null,
    var ttl: Int,
    val replyTo: String? = null,
    val id: String = UUID.randomUUID().toString(),
    val senderRole: UserRole = UserRole.ATTENDEE,
    val presentationId: String? = null
) {

    /**
     * Serialize message into bytes for Nearby Payload
     */
    fun toBytes(): ByteArray {
        val b = ProtoBuf.encodeToByteArray(this);

        return b
    }

    /**
     * Adds a body to the message, and encrypts its contents
     */
    fun <T> addBody(serializer: KSerializer<T>, obj: T): Message {
        // Convert class to byte array
        val buff = ProtoBuf.encodeToByteArray(serializer,obj);

       // Encrypt data
       //TODO: Finish this


       data = buff;

        return this
    }

    fun <T> decodeBody(serializer: KSerializer<T>): T {
        if(data == null) {
            throw Error("Data is missing")
        }
        // TODO: Should need to decrypt byte array
        val decodedBody: T = ProtoBuf.decodeFromByteArray<T>(serializer,data!!);

        return decodedBody
    }

    companion object {



        /**
         * Deserialize from Nearby payload
         */
        fun fromBytes(bytes: ByteArray): Message {
            val m = ProtoBuf.decodeFromByteArray<Message>(bytes);

            return m
        }

        private fun putWithLength(buffer: ByteBuffer, bytes: ByteArray) {
            buffer.putInt(bytes.size)
            buffer.put(bytes)
        }

        private fun readString(buffer: ByteBuffer): String {
            val length = buffer.int
            val bytes = ByteArray(length)
            buffer.get(bytes)
            return String(bytes, StandardCharsets.UTF_8)
        }

        private fun readBytes(buffer: ByteBuffer): ByteArray {
            val length = buffer.int
            val bytes = ByteArray(length)
            buffer.get(bytes)
            return bytes
        }
    }

    // ------------------- Helpers -------------------

    /**
     * Creates a reply message preserving correlation
     */
    fun createReply(
        from: String,
        type: MessageType,
        data: ByteArray?,
        ttl: Int,
        role: UserRole = UserRole.ATTENDEE,
        presentationId: String? = null
    ): Message {
        return Message(
            to = this.from,
            from = from,
            type = type,
            data = data,
            ttl = ttl,
            replyTo = this.id,
            senderRole = role,
            presentationId = presentationId
        )
    }

    /**
     * Decrement TTL safely (for mesh forwarding)
     */
    fun decrementTtl(): Boolean {
        ttl -= 1
        return ttl > 0
    }


     // ----------------- AUTO GENERATED by Android Studio ---------------------------

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Message

        if (ttl != other.ttl) return false
        if (to != other.to) return false
        if (from != other.from) return false
        if (type != other.type) return false
        if (!data.contentEquals(other.data)) return false
        if (replyTo != other.replyTo) return false
        if (id != other.id) return false
        if (senderRole != other.senderRole) return false
        if (presentationId != other.presentationId) return false

        return true
    }

    override fun hashCode(): Int {
        var result = ttl
        result = 31 * result + to.hashCode()
        result = 31 * result + from.hashCode()
        result = 31 * result + type.hashCode()
        result = 31 * result + (data?.contentHashCode() ?: 0)
        result = 31 * result + (replyTo?.hashCode() ?: 0)
        result = 31 * result + id.hashCode()
        result = 31 * result + senderRole.hashCode()
        result = 31 * result + (presentationId?.hashCode() ?: 0)
        return result
    }
}